{"title": "Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands above your shoulders, elbows bent and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing the handles forward towards your kness, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Prone Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the handles with your hands below your shoulders, elbows bent and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles back towards the sides of your buttocks, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Kneeling Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the glideboard and hold the handles in front of your chest, elbows bent and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles back, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms and upper body in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Single-Arm Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold one handle with the hand furthest to it in front of your chest, elbow bent and palm facing your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle back, straightening your arm and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arm and upper body in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles with your arms extended above your knees, palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Single-Arm Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold the handle with the hand closest to it, arm extended and palm facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle towards your shoulder and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arm in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lying Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, and hold the handles with your arms extended and lying on the mat, palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms pressed against the slideboard throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Crunching", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your arms extended, palms facing up and raise your upper body from up the mat.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper body off the glideboard and your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, legs extended and tilt your upper body forward to hold the handles above your ankles, arms extended and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoudlers while raising your upper body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pulling the handles and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles with your hands above your knees, arms extended, palms facing up and attach your ankles to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chin-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the wing attachment with your hands, arms extended and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pulling yourself up and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Close-Grip Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and towards each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide-Grip Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and away from each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Incline Push Up", "content": "<ul>\n\t\t\t\t\t<li>Lie face down with your hands on the glideboard and your feet on the base of the rails, back and legs fully extended and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Push yourself up by extending your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back and legs fully extended throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other, arms parallel to the floor other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Incline Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other and up in front of your head and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Decline Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other and down in front of your abdomen and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard with your legs extended out and hold one handle with the hand closest to it, arm extended out with your elbow only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle towards the front of your chest and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time rolling your shoulder blades up and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Twisting Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling one handle down towards the opposite thigh while at the same time rolling your shoulder blades up and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, feet against the squat stand and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single Leg Pullover with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, one knee bent and its foot against the squat stand while the other leg is extended out and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time extending your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Press", "content": "<ul>\n\t\t\t\t\t<li>Lie face down on the glideboard, knees bent and grasp the press-up bars with your hands, elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by extending your arms (pushing yourself up) and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pushing and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard and hold the handles down above your ankles, arms and legs extended, palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders while raising your back and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended, palms facing down and ankles attached using the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles down near your hips, arms fully extended, palms facing each other.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles outwardly towards the level of your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing back.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide Grip Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing back.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward and outward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise with Supination Grip", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing forward.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lying Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles down near your hips, arms fully extended, plams facing each down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up until your arms are perpendicular to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles down near your thighs, arms extended, plams facing back and ankles attached to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight up in front of you while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the glideboard and crouch to hold the handles with your arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor while raising your upper body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet pressed against the squat stand and your hands against your ears.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the gildeboard while keeping your lower back in contact with it and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Resisted Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your knees bent and your feet on the glideboard and hold the handles with your hands, arms extended out and parallel to your thighs.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard by pushing on the handles while keeping your arms extended and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Inclined Crunch with Feet Attached", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your head down, feet attched to the wing attachment, knees slightly bent.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard while keeping your lower back in contact with it and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crunch with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your head down, feet attched to the wing attachment, knees slightly bent.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard while at the same time pulling yourself up closer to your feet by bending your knees and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles near your knees, arms extended, palms facing down and ankles attached to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Arm Pull", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold one handle with the hand opposite to it, arms extended and palm facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle straight back while keeping it at the same height off the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Sit-Up with Feet Attached", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet attached to the wing attachment and place your hands across your chest.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Sit-Up with Cable", "content": "<ul>\n\t\t\t\t\t<li>Sit down on the glideboard looking up, knees bent and hold the handles with your hands, arms extended.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Trunk Rotation", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard, keep your legs extended up from the floor and hold the handles with both hands close to one another on your side.<br><br></li>\n\t\t\t\t\t<li>While keeping the angles in your elbows still, pull the handles towards the other side of your trunk and allow yourself back to the starting position after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jacknife Sit-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet pressed against the squat stand and extend your arms up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and until your arms are parallel to your legs and lower yourself down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Try to keep your back, legs and arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "High Leg Pull-In", "content": "<ul>\n\t\t\t\t\t<li>Kneel down on the glideboard, grasp the toe bar with your hands and push your body up the rail while keeping your thighs and upper body extended on the same line.<br><br></li>\n\t\t\t\t\t<li>Pull yourself back towards the toe bar while keeping your arms and upper body fully extended and push yourself back up after a short pause.<br><br></li>\n\t\t\t\t\t<li>Be careful not to back yourself too far out up to a point where you would lose balance.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Low Leg Pull-In", "content": "<ul>\n\t\t\t\t\t<li>Kneel down on the glideboard, grasp the base of the machine with your hands and push your body up the rail so that your body is fully extended.<br><br></li>\n\t\t\t\t\t<li>Pull yourself back towards your hands by bending your hips and knees and push yourself back up after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms extended and perpendicular to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Side Plank", "content": "<ul>\n\t\t\t\t\t<li>Rest on one side on your forearm (elbow at 90 degrees), body fully extended with your feet against the base of the machine.<br><br></li>\n\t\t\t\t\t<li>Bring the arm that is free up above your head and extend it so that is parallel to the mat and hold for a few seconds before bringing it back.<br><br></li>\n\t\t\t\t\t<li>Only the arm that is free should be moving throughout the exercise.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your legs extended and attach your ankles to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while curling your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Reverse Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, hips and knees at 90 degree angles and rest your feet against the toe raise bar.<br><br></li>\n\t\t\t\t\t<li>Raise your buttocks from up the glideboard by straightening your hips and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep a 90 degree angle in your knees throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet wide from each other on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with one foot on the squat stand with its knee at a 90 degree angles and the other leg slightly elevated and extended.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat On Side", "content": "<ul>\n\t\t\t\t\t<li>Lie sideways on the glideboard with one foot on the squat stand, its knee at a 90 degree angle and the other off the squat stand, knee bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat Kneeling", "content": "<ul>\n\t\t\t\t\t<li>Kneel on one knee on the glideboard with the other foot resting against the squat stand, its knee bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jumping Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by jumping slightly off the squat stand and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while jumping and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Twisting Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles, rotated out slightly to one side.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs while realigning yourself and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jumping and Twisting Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles, rotated out slightly to one side.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by jumping slightly off the squat stand while realigning yourself and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while jumping and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Lunge", "content": "<ul>\n\t\t\t\t\t<li>Stand in front of the glideboard and put one foot on it, knee slightly bent, both feet pointing forward.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing your foot foward and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight and perpendicular to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Extension with Knee Stabilized", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and attach one foot to the leg pull attachment, its leg straight and perpendicular to the floor.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your leg down and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your leg straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Abduction", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard, legs straight and feet resting against and inside the cables and hold the handles with your hands, palms facing each other.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your legs away from each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your legs and back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Adduction", "content": "<ul>\n\t\t\t\t\t<li>Lie sideways on the glideboard with one foot attached to the leg pull attachment, its leg straight and prependicular to the floor.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your leg down towards the other one and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your leg straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Calf Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard and place only your toes on the squat stand.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on your toes to raise your heels and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pushing and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and rest your hands against your lower back.<br><br></li>\n\t\t\t\t\t<li>Raise your upper body from the glideboard as high as you can by contracting your lower back muscles and bring yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>You may rest your hands behind your head to add a further level of difficulty.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crossover Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles in a crossover fashion with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Kneeling Row", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Row with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your legs fully extended and crouch down to hold the handles with your hands, arms fully extended in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up while raising your upper body up by pulling the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Rotating Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on one handle towards its side of your body and allow yourself back down after a short pause. Alternate sides between repetitions.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Prone Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the handles with your hands, arms extended out.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Back Fly with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the bench, attach your feet to the wing attachment and hold the handles with your hands, arms fully extended in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body while curling your knees and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Pulldown", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, and hold the handles with your hands, arms extended out to each side of your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your buttocks and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pulldown with Squat with Elbows Flexed", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, feet on the squat stand with your knees bent and hold the handles with your hands above your head, elbows slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards your abdomen while extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Pulldown with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, feet on the squat stand with your knees bent and hold the handles with your hands above your head, elbows slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body while extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pull-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the wing attachment with your hands, plams facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your elbows until your head is above it and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands above your shoulders, elbows bent and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing the handles forward towards your kness, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Prone Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the handles with your hands below your shoulders, elbows bent and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles back towards the sides of your buttocks, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Kneeling Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the glideboard and hold the handles in front of your chest, elbows bent and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles back, straightening your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms and upper body in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Single-Arm Triceps Extension", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold one handle with the hand furthest to it in front of your chest, elbow bent and palm facing your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle back, straightening your arm and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arm and upper body in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your legs extended and attach your ankles to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while curling your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Reverse Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, hips and knees at 90 degree angles and rest your feet against the toe raise bar.<br><br></li>\n\t\t\t\t\t<li>Raise your buttocks from up the glideboard by straightening your hips and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep a 90 degree angle in your knees throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet wide from each other on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with one foot on the squat stand with its knee at a 90 degree angles and the other leg slightly elevated and extended.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat On Side", "content": "<ul>\n\t\t\t\t\t<li>Lie sideways on the glideboard with one foot on the squat stand, its knee at a 90 degree angle and the other off the squat stand, knee bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single-Leg Squat Kneeling", "content": "<ul>\n\t\t\t\t\t<li>Kneel on one knee on the glideboard with the other foot resting against the squat stand, its knee bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your leg and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jumping Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by jumping slightly off the squat stand and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while jumping and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Twisting Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles, rotated out slightly to one side.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by straightening your legs while realigning yourself and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while straightening your legs and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jumping and Twisting Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard with your feet on the squat stand, knees at 90 degree angles, rotated out slightly to one side.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by jumping slightly off the squat stand while realigning yourself and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while jumping and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Lunge", "content": "<ul>\n\t\t\t\t\t<li>Stand in front of the glideboard and put one foot on it, knee slightly bent, both feet pointing forward.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing your foot foward and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight and perpendicular to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Extension with Knee Stabilized", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and attach one foot to the leg pull attachment, its leg straight and perpendicular to the floor.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your leg down and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your leg straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Abduction", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard, legs straight and feet resting against and inside the cables and hold the handles with your hands, palms facing each other.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your legs away from each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your legs and back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hip Adduction", "content": "<ul>\n\t\t\t\t\t<li>Lie sideways on the glideboard with one foot attached to the leg pull attachment, its leg straight and prependicular to the floor.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling your leg down towards the other one and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your leg straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Calf Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard and place only your toes on the squat stand.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on your toes to raise your heels and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pushing and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles with your arms extended above your knees, palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Single-Arm Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold the handle with the hand closest to it, arm extended and palm facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle towards your shoulder and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arm in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lying Biceps Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, and hold the handles with your arms extended and lying on the mat, palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms pressed against the slideboard throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Crunching", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your arms extended, palms facing up and raise your upper body from up the mat.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper body off the glideboard and your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, legs extended and tilt your upper body forward to hold the handles above your ankles, arms extended and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoudlers while raising your upper body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pulling the handles and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Biceps Curl with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles with your hands above your knees, arms extended, palms facing up and attach your ankles to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles towards your shoulders while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your upper arms in the same position throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chin-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the wing attachment with your hands, arms extended and palms facing up.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pulling yourself up and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and rest your hands against your lower back.<br><br></li>\n\t\t\t\t\t<li>Raise your upper body from the glideboard as high as you can by contracting your lower back muscles and bring yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>You may rest your hands behind your head to add a further level of difficulty.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Press", "content": "<ul>\n\t\t\t\t\t<li>Lie face down on the glideboard, knees bent and grasp the press-up bars with your hands, elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by extending your arms (pushing yourself up) and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while pushing and breathe in while returning to starting position.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard and hold the handles down above your ankles, arms and legs extended, palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders while raising your back and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crossover Row", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles in a crossover fashion with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Kneeling Row", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Row with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your legs fully extended and crouch down to hold the handles with your hands, arms fully extended in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up while raising your upper body up by pulling the handles towards the sides of your navel and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Rotating Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the glideboard and hold the handles with your hands, arms extended out in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on one handle towards its side of your body and allow yourself back down after a short pause. Alternate sides between repetitions.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet pressed against the squat stand and your hands against your ears.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the gildeboard while keeping your lower back in contact with it and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Resisted Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your knees bent and your feet on the glideboard and hold the handles with your hands, arms extended out and parallel to your thighs.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard by pushing on the handles while keeping your arms extended and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Inclined Crunch with Feet Attached", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your head down, feet attched to the wing attachment, knees slightly bent.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard while keeping your lower back in contact with it and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Crunch with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your head down, feet attched to the wing attachment, knees slightly bent.<br><br></li>\n\t\t\t\t\t<li>Roll your shoulder blades up from the glideboard while at the same time pulling yourself up closer to your feet by bending your knees and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Sit-Up with Feet Attached", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet attached to the wing attachment and place your hands across your chest.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Sit-Up with Cable", "content": "<ul>\n\t\t\t\t\t<li>Sit down on the glideboard looking up, knees bent and hold the handles with your hands, arms extended.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and lower yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>To avoid pulling your neck with your hands, look straight up instead of looking at your knees.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Trunk Rotation", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard, keep your legs extended up from the floor and hold the handles with both hands close to one another on your side.<br><br></li>\n\t\t\t\t\t<li>While keeping the angles in your elbows still, pull the handles towards the other side of your trunk and allow yourself back to the starting position after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Jacknife Sit-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie down on your back with your feet pressed against the squat stand and extend your arms up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Roll your upper body up until your lower back no longer touches the glideboard and until your arms are parallel to your legs and lower yourself down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Try to keep your back, legs and arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "High Leg Pull-In", "content": "<ul>\n\t\t\t\t\t<li>Kneel down on the glideboard, grasp the toe bar with your hands and push your body up the rail while keeping your thighs and upper body extended on the same line.<br><br></li>\n\t\t\t\t\t<li>Pull yourself back towards the toe bar while keeping your arms and upper body fully extended and push yourself back up after a short pause.<br><br></li>\n\t\t\t\t\t<li>Be careful not to back yourself too far out up to a point where you would lose balance.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Low Leg Pull-In", "content": "<ul>\n\t\t\t\t\t<li>Kneel down on the glideboard, grasp the base of the machine with your hands and push your body up the rail so that your body is fully extended.<br><br></li>\n\t\t\t\t\t<li>Pull yourself back towards your hands by bending your hips and knees and push yourself back up after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms extended and perpendicular to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Side Plank", "content": "<ul>\n\t\t\t\t\t<li>Rest on one side on your forearm (elbow at 90 degrees), body fully extended with your feet against the base of the machine.<br><br></li>\n\t\t\t\t\t<li>Bring the arm that is free up above your head and extend it so that is parallel to the mat and hold for a few seconds before bringing it back.<br><br></li>\n\t\t\t\t\t<li>Only the arm that is free should be moving throughout the exercise.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Close-Grip Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and towards each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide-Grip Chest Press", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing down and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pushing on the handles straight forward and away from each other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your forearms parallel to the floor throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Incline Push Up", "content": "<ul>\n\t\t\t\t\t<li>Lie face down with your hands on the glideboard and your feet on the base of the rails, back and legs fully extended and elbows bent.<br><br></li>\n\t\t\t\t\t<li>Push yourself up by extending your arms and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back and legs fully extended throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other, arms parallel to the floor other and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Incline Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other and up in front of your head and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Decline Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard with your knees bent and hold the handles with your hands on each side of your chest, palms facing each other and elbows only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles close to each other and down in front of your abdomen and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Chest Fly", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard with your legs extended out and hold one handle with the hand closest to it, arm extended out with your elbow only slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle towards the front of your chest and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time rolling your shoulder blades up and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Twisting Crunch", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling one handle down towards the opposite thigh while at the same time rolling your shoulder blades up and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pullover with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, feet against the squat stand and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Single Leg Pullover with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, one knee bent and its foot against the squat stand while the other leg is extended out and hold the handles with your hands, arms extended up in line with your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles down towards your thighs while at the same time extending your leg and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Upright Row with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended, palms facing down and ankles attached using the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up towards your shoulders while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles down near your hips, arms fully extended, palms facing each other.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles outwardly towards the level of your shoulders and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing back.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Wide Grip Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing back.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward and outward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise with Supination Grip", "content": "<ul>\n\t\t\t\t\t<li>Sit on the glideboard, knees slightly bent and hold the handles down below your buttocks, arms extended and palms facing forward.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles forward until your arms are parallel to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lying Front Deltoid Raise", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent and hold the handles down near your hips, arms fully extended, plams facing each down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles up until your arms are perpendicular to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Front Deltoid Raise with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles down near your thighs, arms extended, plams facing back and ankles attached to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight up in front of you while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles above your knees, arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension with Hyperextension", "content": "<ul>\n\t\t\t\t\t<li>Kneel on the glideboard and crouch to hold the handles with your arms extended and palms facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor while raising your upper body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Shoulder Extension with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top end of the glideboard and hold the handles near your knees, arms extended, palms facing down and ankles attached to the wing attachment.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handles straight back until your arms are perpendicular to the floor while curling your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Arm Pull", "content": "<ul>\n\t\t\t\t\t<li>Sit sideways on the glideboard and hold one handle with the hand opposite to it, arms extended and palm facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling the handle straight back while keeping it at the same height off the floor and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Prone Back Fly", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the handles with your hands, arms extended out.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Back Fly with Leg Curl", "content": "<ul>\n\t\t\t\t\t<li>Sit on the top edge of the bench, attach your feet to the wing attachment and hold the handles with your hands, arms fully extended in front of you.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body while curling your knees and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your back straight throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Pulldown", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, knees bent, and hold the handles with your hands, arms extended out to each side of your body.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your buttocks and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep your arms fully extended throughout (or keep the small bend in your elbows constant).<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pulldown with Squat with Elbows Flexed", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, feet on the squat stand with your knees bent and hold the handles with your hands above your head, elbows slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards your abdomen while extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Lateral Pulldown with Squat", "content": "<ul>\n\t\t\t\t\t<li>Lie on your back on the glideboard, feet on the squat stand with your knees bent and hold the handles with your hands above your head, elbows slightly bent.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by pulling on the handles towards the sides of your body while extending your legs and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Keep the small bend in your elbows constant throughout.<br><br></li>\n\t\t\t\t </ul>"}
{"title": "Pull-Up", "content": "<ul>\n\t\t\t\t\t<li>Lie prone on the glideboard and hold the wing attachment with your hands, plams facing down.<br><br></li>\n\t\t\t\t\t<li>Slide the glideboard up by curling your elbows until your head is above it and allow yourself back down after a short pause.<br><br></li>\n\t\t\t\t\t<li>Breathe out while raising yourself and breathe in while lowering yourself back.<br><br></li>\n\t\t\t\t </ul>"}
